### Crear un nuevo libro (POST)

POST http://localhost:5000/libros
Content-Type: application/json

{
  "titulo": "Flask Avanzado",
  "autor": "Miguel Grinberg",
  "anio_publicacion": 2024,
  "genero": "Programación",
  "url": "https://flask.palletsprojects.com/",
  "notas": "Libro recomendado para desarrolladores web.",
  "etiquetas": "flask,python,web",
  "propietario_id": 1
}