### Editar un libro (PUT)

PUT http://localhost:5000/libros/4
Content-Type: application/json

{
  "titulo": "Libro actualizado",
  "autor": "Nuevo Autor",
  "anio_publicacion": 2024,
  "genero": "Actualizado",
  "url": "https://ejemplo.com/actualizado",
  "notas": "Notas actualizadas",
  "etiquetas": "actualizado, prueba"
}